server:
  port: 8090
  servlet:
    context-path: /bbgu

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbgu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: bbgu
    password: bxhXtrYfEWjyx8n2
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      location: /www/wwwroot/api/bbgu/images/

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.chennyh.bbgunews.dao: info

springfox:
  documentation:
    swagger-ui:
      enabled: false
